everywhere/Everywhere Admin UI/Everywhere Admin UI/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Everywhere_Admin_UI.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult VideoSettings()
        {
            return View();
        }
    }
}

everywhere/Everywhere Admin UI/Everywhere Admin UI/Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
    <title>@ViewBag.Title - Everywhere Web</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
    <link class="gf-headline" href="https://fonts.googleapis.com/css?family=Pacifico:400&amp;subset=" rel="stylesheet" type="text/css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header data-spy="affix" data-offset-top="460" data-offset-bottom="200">
        <nav class="navbar navbar-admin" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-main">*@
                        @*<a href="#" class="dropdown-toggle" id="userName" data-toggle="dropdown"><b class="caret"></b></a>*@
                   @* </button>*@
                    <a class="navbar-brand" href="#">
                        <span class="brand-icon"><img src="~/Images/everywhere_logo_admin.png"></span>
                        <span class="brand-text"> everywhere<sup>™</sup></span>
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-collapse-main">
                    <div class="navbar-right">
                        <ul class="nav navbar-nav navbar-center">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" id="userName" aria-expanded="false"> <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#" onclick="Logout()">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
        <nav class="navbar-main" role="navigation">
            <div class="container-max">
                <ul class="nav nav-pills nav-justified">
                    <li>
                        <a href="#" onclick="@("window.location.href='" + @Url.Action("UserManagement", "Manage") + "'");">
                            <span class="visible-xs"><i class="glyphicon glyphicon-user"></i></span>
                            <span class="hidden-xs">User Management</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" onclick="@("window.location.href='" + @Url.Action("ServicesManagement", "Account") + "'");">
                            <span class="visible-xs"><i class="glyphicon glyphicon-th-large"></i></span>
                            <span class="hidden-xs">Services Management</span>
                        </a>
                    </li>
                    <li>
                        <a href="#" onclick="@("window.location.href='" + @Url.Action("AdminManagement", "Account") + "'");">
                            <span class="visible-xs"><i class="glyphicon glyphicon-pawn"></i></span>
                            <span class="hidden-xs">Admin User Management</span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="visible-xs"><i class="glyphicon glyphicon-cog"></i></span>
                            <span class="hidden-xs">Settings</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#" onclick="@("window.location.href='" + @Url.Action("ProfileSettings", "Account") + "'");">Profile Settings</a></li>
                            <li><a href="#" onclick="@("window.location.href='" + @Url.Action("VideoSettings", "Video") + "'");">Video Switch Settings</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>

    </header>

    @RenderBody()
    <footer> <span>© 2016 Intercept Technologies, Inc.</span> </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<script type="text/javascript">
    function Logout() {
        ;   
        var token = sessionStorage.getItem('loginToken');
        var headers = {};
        if (token) {
            headers.Authorization = 'Bearer ' + token;
        }
        $.ajax({
            url: apiUrl+"api/v1/signout/",
            type: "GET",
            crossDomain: true,
            data: {},
            dataType: "json",
            headers: headers,
            async: false,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                var url = '@Url.Action("Login", "Account")';
                window.location.href = url;
            },
            error: function (jqXhr, textStatus, errorThrown) {
                var url = '@Url.Action("Login", "Account")';
                window.location.href = url;
            }
        });
    }
</script>    

everywhere/Everywhere Admin UI/Everywhere Admin UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
    <title>@ViewBag.Title - Everywhere Web</title>
  
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
    <link class="gf-headline" href="https://fonts.googleapis.com/css?family=Pacifico:400&amp;subset=" rel="stylesheet" type="text/css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
        @RenderBody()
    <footer> <span>© 2016 Intercept Technologies, Inc.</span> </footer>
 
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>